# Generated by Django 4.1.5 on 2023-01-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название профессии')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видно на сайте?')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='ProfessionDescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', max_length=500, verbose_name='Заголовок описания')),
                ('description', models.TextField(default='Без описания', verbose_name='Текст описания')),
            ],
            options={
                'verbose_name': 'Описание профессии',
                'verbose_name_plural': 'Описание профессий',
                'db_table': 'profession_descriptions',
            },
        ),
        migrations.CreateModel(
            name='YearDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_title', models.CharField(default='Заголовок диаграммы', max_length=200, verbose_name='Заголовок диаграммы')),
                ('image', models.BinaryField(default=None, null=True, verbose_name='Картинка в бинарном виде')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Годовая диаграмма',
                'verbose_name_plural': 'Годовые диаграммы',
                'db_table': 'year_diagrams',
            },
        ),
        migrations.CreateModel(
            name='VacanciesDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_title', models.CharField(default='Заголовок диаграммы', max_length=200, verbose_name='Заголовок диаграммы')),
                ('image', models.BinaryField(default=None, null=True, verbose_name='Картинка в бинарном виде')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Диаграмма вакансий',
                'verbose_name_plural': 'Диаграммы вакансий',
                'db_table': 'vacancy_diagrams',
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='description_blocks',
            field=models.ManyToManyField(to='app.professiondescriptionblock', verbose_name='Блоки описания профессии'),
        ),
        migrations.CreateModel(
            name='CitiesVacanciesDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_title', models.CharField(default='Заголовок диаграммы', max_length=200, verbose_name='Заголовок диаграммы')),
                ('image', models.BinaryField(default=None, null=True, verbose_name='Картинка в бинарном виде')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Диаграмма ваканский по городам',
                'verbose_name_plural': 'Диаграммы ваканский по городам',
                'db_table': 'city_vacancy_diagrams',
            },
        ),
        migrations.CreateModel(
            name='CitiesDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_title', models.CharField(default='Заголовок диаграммы', max_length=200, verbose_name='Заголовок диаграммы')),
                ('image', models.BinaryField(default=None, null=True, verbose_name='Картинка в бинарном виде')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Диаграмма по городам',
                'verbose_name_plural': 'Диаграммы по городам',
                'db_table': 'city_diagrams',
            },
        ),
    ]
