# Generated by Django 4.1.5 on 2023-01-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
                'db_table': 'skill_years',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название навыка')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Востребованность')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.year', verbose_name='Год навыка')),
            ],
            options={
                'verbose_name': 'Навык года',
                'verbose_name_plural': 'Навыки года',
                'db_table': 'skills',
            },
        ),
    ]
