# Generated by Django 4.1.5 on 2023-01-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_year_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='citiesdiagram',
            name='image_raw',
            field=models.ImageField(default='media/default/no_image.png', upload_to='media/uploads/', verbose_name='Картинка в чистом виде'),
        ),
        migrations.AddField(
            model_name='citiesvacanciesdiagram',
            name='image_raw',
            field=models.ImageField(default='media/default/no_image.png', upload_to='media/uploads/', verbose_name='Картинка в чистом виде'),
        ),
        migrations.AddField(
            model_name='vacanciesdiagram',
            name='image_raw',
            field=models.ImageField(default='media/default/no_image.png', upload_to='media/uploads/', verbose_name='Картинка в чистом виде'),
        ),
        migrations.AddField(
            model_name='yeardiagram',
            name='image_raw',
            field=models.ImageField(default='media/default/no_image.png', upload_to='media/uploads/', verbose_name='Картинка в чистом виде'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description_blocks',
            field=models.ManyToManyField(blank=True, to='app.professiondescriptionblock', verbose_name='Блоки описания профессии'),
        ),
    ]
