# Generated by Django 4.1.5 on 2023-01-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_citiesdiagram_image_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видно на сайте?'),
        ),
    ]
