# Generated by Django 4.1.5 on 2023-01-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_year_profession_alter_year_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='description_blocks',
        ),
        migrations.AddField(
            model_name='professiondescriptionblock',
            name='profession',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profession', verbose_name='Профессия'),
        ),
    ]
